<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JadeCapital.Identity.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.19" />
    <PackageReference Include="FluentValidation" Version="11.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\3.Shared\JadeCapital.Shared.Kernel\JadeCapital.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\3.Shared\JadeCapital.Shared.Infrastructure\JadeCapital.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\JadeCapital.Identity.Domain\JadeCapital.Identity.Domain.csproj" />
    <ProjectReference Include="..\JadeCapital.Identity.Contracts\JadeCapital.Identity.Contracts.csproj" />
  </ItemGroup>
</Project>