<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JadeCapital.Identity.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <ProjectReference Include="..\..\..\3.Shared\JadeCapital.Shared.Kernel\JadeCapital.Shared.Kernel.csproj" />
  </ItemGroup>
</Project>