// SPDX-License-Identifier: Proprietary
//
// Wave 11 slice 11.4 — removed the <auto-generated-by>Wave 10 slice 10.2</auto-generated-by>
// marker from line 1 (the previous opener labelled this file as
// auto-generated; it has been hand-edited since then). Wave 10 slice 10.2
// original header preserved here for git-blame continuity.
//
// Wave 10 slice 10.2 - Docker Secrets adapter for IConfiguration.
//
// WHAT
//   Reads every file mounted under `/run/secrets/` (the directory used by
//   Docker Swarm/Services + docker compose `secrets:` blocks) and projects
//   each one into the configuration tree under the `__Secret:<name>` key.
//
// WHY
//   We intentionally avoid `IConfigurationProvider`-specific knowledge
//   across the rest of the codebase. Anywhere in the app we read a secret
//   via `IConfiguration["__Secret:<name>"]` or
//   `IConfiguration.GetValue<string>("__Secret:<name>")`. The actual backing
//   store (Docker Secrets file mounts today, Vault / AWS SM / Doppler
//   tomorrow) is a swappable detail.
//
// DESIGN NOTES
//   * Silent-skip when `/run/secrets/` is absent: dev boxes + CI runners
//     don't have a Docker swarm mount, and they should not crash. The
//     provider becomes a no-op in that case.
//   * `.Trim()` on every value: Docker Secrets are mounted as raw file
//     contents; a trailing newline is the rule, not the exception.
//   * `__Secret:` prefix is intentional - prevents accidental collisions
//     with environment variables (`Jwt:AccessTokenSecret` is bound via
//     the standard `__` section separator; the prefix makes the source
//     obvious in logs without being invasive).
//   * Testability: the secrets directory is constructor-injectable (with
//     `/run/secrets` as the production default) so unit tests can target a
//     temporary directory without going through reflection.

using Microsoft.Extensions.Configuration;

namespace JadeCapital.Host.Configuration;

/// <summary>
/// Configuration provider that materializes Docker Secrets (files mounted at
/// <c>/run/secrets/&lt;name&gt;</c>) as configuration keys in the format
/// <c>__Secret:&lt;name&gt;</c>. Reads are populated lazily via
/// <see cref="Load"/>; rewatches are not supported - restart the host to
/// pick up a rotated secret.
/// </summary>
public sealed class DockerSecretConfigurationProvider : ConfigurationProvider
{
    /// <summary>
    /// Docker convention: secrets are mounted at <c>/run/secrets/</c> by
    /// default. We hard-code the production default because every Docker
    /// engine since 2017 honors it; deviating would mean overriding the
    /// daemon flag.
    /// </summary>
    public const string DefaultSecretsDirectory = "/run/secrets";

    /// <summary>
    /// Configuration key prefix. Applications read secrets via
    /// <c>IConfiguration["__Secret:postgres_password"]</c>.
    /// </summary>
    public const string ConfigPrefix = "__Secret:";

    private readonly string _secretsDirectory;

    /// <summary>
    /// Production constructor: reads from the Docker engine default
    /// <c>/run/secrets</c> mount.
    /// </summary>
    public DockerSecretConfigurationProvider()
        : this(DefaultSecretsDirectory)
    {
    }

    /// <summary>
    /// Test seam - allows a temporary directory to be passed in. Kept
    /// public (instead of <c>internal</c>) so that downstream test
    /// projects can drive the provider without an InternalsVisibleTo.
    /// </summary>
    /// <param name="secretsDirectory">
    /// Absolute path to a directory containing one file per secret; each
    /// filename becomes the configuration key (sans prefix).
    /// </param>
    public DockerSecretConfigurationProvider(string secretsDirectory)
    {
        if (string.IsNullOrWhiteSpace(secretsDirectory))
            throw new System.ArgumentException(
                "Secrets directory must be a non-empty path.",
                nameof(secretsDirectory));
        _secretsDirectory = secretsDirectory;
    }

    /// <summary>
    /// Populate <see cref="ConfigurationProvider.Data"/> from files
    /// mounted under the configured secrets directory. Silently no-ops
    /// when the directory is absent (dev / CI); throws
    /// <see cref="System.IO.IOException"/> when the directory exists but
    /// a file cannot be read.
    /// </summary>
    public override void Load()
    {
        if (!Directory.Exists(_secretsDirectory))
        {
            // No Docker Secrets directory - fall through to env vars /
            // appsettings.json. Do NOT throw; this keeps the host bootable
            // on a dev machine without a swarm mount.
            return;
        }

        foreach (var secretFile in Directory.EnumerateFiles(_secretsDirectory))
        {
            var name = Path.GetFileName(secretFile);
            var value = File.ReadAllText(secretFile).Trim();
            Data[$"{ConfigPrefix}{name}"] = value;
        }
    }

    /// <summary>
    /// Read-only view of the loaded secrets as
    /// <c>__Secret:&lt;name&gt; -&gt; value</c> pairs. Public so unit
    /// tests (and a future <c>/health/secrets</c> admin probe) can
    /// introspect what was loaded without exposing the writable
    /// <see cref="ConfigurationProvider.Data"/> dictionary directly.
    /// </summary>
    public IReadOnlyDictionary<string, string> GetLoadedSecrets()
        => (IReadOnlyDictionary<string, string>)Data;
}

/// <summary>
/// Configuration source that builds a <see cref="DockerSecretConfigurationProvider"/>.
/// Wired in <c>Program.cs</c> via
/// <c>builder.Configuration.Add(new DockerSecretConfigurationSource())</c>.
/// </summary>
public sealed class DockerSecretConfigurationSource : IConfigurationSource
{
    private readonly string _secretsDirectory;

    /// <summary>
    /// Production constructor: targets <c>/run/secrets</c>.
    /// </summary>
    public DockerSecretConfigurationSource()
        : this(DockerSecretConfigurationProvider.DefaultSecretsDirectory)
    {
    }

    /// <summary>
    /// Test seam - pass an alternate secrets directory.
    /// </summary>
    public DockerSecretConfigurationSource(string secretsDirectory)
    {
        _secretsDirectory = secretsDirectory;
    }

    public IConfigurationProvider Build(IConfigurationBuilder builder)
        => new DockerSecretConfigurationProvider(_secretsDirectory);
}
