<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JadeCapital.PublicPortal.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="FluentValidation" Version="11.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\3.Shared\JadeCapital.Shared.Kernel\JadeCapital.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\Billing\JadeCapital.Billing.Contracts\JadeCapital.Billing.Contracts.csproj" />
  </ItemGroup>
</Project>