<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JadeCapital.Admin.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\3.Shared\JadeCapital.Shared.Kernel\JadeCapital.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\Identity\JadeCapital.Identity.Contracts\JadeCapital.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Billing\JadeCapital.Billing.Contracts\JadeCapital.Billing.Contracts.csproj" />
    <ProjectReference Include="..\..\Trading\JadeCapital.Trading.Contracts\JadeCapital.Trading.Contracts.csproj" />
  </ItemGroup>
</Project>